version: "3.8"

services: 
  client: 
    image: rolitoxdd/weechat
    build: ./weechat
    depends_on: 
      - server
    cap_add:
      - NET_ADMIN

  server:
    image: rolitoxdd/oragono
    build: ./oragono
